// Create a Calculator :-
#include<conio.h>
#include<iostream.h>
void main()
{
 int a;
 int b;
 clrscr();
 cout<< " Enter number: " << endl;
 cin>>a;
 cout<< "Enter other number: "<<endl;
 cin>>b;
 // Calculate sum
 int sum;
 sum=a+b;
 cout<< " sum is \t :"<<sum<<endl;
 // Calculate subtraction
 int sub;
 sub=a-b;
 cout<< " subtraction is  :"<<sub<<endl;
 // Calculate multiply
 int multi;
 multi=a*b;
 cout<< " multiply is \t :"<<multi<<endl;
 // Calculate division
 float division;
 division=a/b;
 cout<< " division is \t :"<<division<<endl;
 getch();
 }










