#include<conio.h>
#include<iostream.h>
void main()
 {
   char a;
   clrscr();
   cout<<"Enter a symbol : " ;
   cin>>a;
   if(a==*)
    cout<< "Sunday";
      else if(a==2)
       cout<<"Monday";
      else if(a==3)
	 cout<<"tuesday";
	 else if(a==4)
       cout<<"wednesday";
	else if(a==5)
       cout<<"thursday ";
       else if(a==6)
	cout<<"Friday";
	else if(a==7)
	cout<<"saturday";
	else
	cout<<"please enter right number";
      getch();
